# Generated by Django 3.2.25 on 2024-11-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.IntegerField()),
                ('english', models.IntegerField()),
                ('science', models.IntegerField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.details')),
            ],
        ),
    ]
